export const microbes_list = [
	'Acinetobacter baumannii',
	'Acinetobacter species',
	'Aerobic spore bearers',
	'Burkholderia cepacia',
	'Burkholderia pseudomallei',
	'Bacteroides species',
	'Bacillus anthracis',
	'Bacillus cereus',
	'Citrobacter freundii',
	'Citrobacter species',
	'Escherichia coli',
	'Enterococcus fecalis',
	'Enterococcus feacium',
	'Enterococcus species',
	'Hafnia species',
	'Hemophilus influenzae',
	'Hemophilus species',
	'Klebsiella pneumoniae',
	'Klebsiella oxytoca',
	'Klebsiella species',
	'Moraxella catarrhalis',
	'Morganella species',
	'Neisserria gonorrhoeae',
	'Neisseria meningitidis',
	'Proteus vulgaris',
	'Proteus mirabilis',
	'Providencia rettgeri',
	'Pseudomonas aeruginosa',
	'Pseudomonas species',
	'Streptococcus pyogenes',
	'Streptococcus agalactiae',
	'Streptococcus pneumoniae',
	'Streptococcus species',
	'Streptococcus - Beta hemolytic',
	'Staphylococcus aureus',
	'Salmonella typhi',
	'Salmonella paratyphi A',
	'Salmonella paratyphi B',
	'Salmonella typhimurium',
	'Salmpnells species',
	'Shigella flexneri',
	'Shigella boydii',
	'Shigella dysentriae',
	'Shigella sonnei',
	'Shigella species',
	'Serratia marcescens',
	'Stenotrphomonas maltophilia',
	'Yersinia entercolitica',
	'Yersinia pestis',
	'other',
]
export const antibiotic_list = [
	'AMIKACIN',
	'AMOXICILLIN CLAVUNATE',
	'AMOXYCILLIN ',
	'AMPICILLIN',
	'AMPICILLIN SULBACTUM',
	'AZITHROMYCIN',
	'CEFAZOLIN',
	'CEFAZOLIN(U)',
	'CEFEPIME',
	'CEFOTAXIME or CEFTRIAXONE',
	'CEFOTETAN',
	'CEFOXITIN',
	'CEFTAZIDIME',
	'CEFUROXIME',
	'CIPROFLOXACIN',
	'CLINDAMYCIN',
	'DAPTOMYCIN',
	'DOXYCYCLINE',
	'ERTAPENEM',
	'ERYTHROMYCIN',
	'FOSFOMYCIN (U)',
	'GENTAMICIN',
	'GENTAMYCIN (HIGH LEVEL)',
	'IMIPENEM',
	'LEVOFLOXACIN',
	'LINEZOLID',
	'MEROPENEM',
	'NITROFURANTOIN(U)',
	'OXACILLIN',
	'PENICILLIN',
	'PIPERACILLIN',
	'TAZOBACTUM',
	'STREPTOMYCIN (HIGH LEVEL)',
	'SULFAMETHOXAZOLE',
	'TETRACYCLINE',
	'TOBRAMYCIN',
	'TRIMETHOPRIM',
	'VANCOMYCIN',
	'other',
]

export const month = [
	'January',
	'February',
	'March',
	'April',
	'May',
	'June',
	'July',
	'August',
	'September',
	'October',
	'November',
	'December',
]

export const dropDown1 = ['Gram Stain', 'Wet Mount ', 'KOH', ' Others']
export const dropDown3 = [
	'Gram Stain',
	'Wet Mount ',
	'KOH',
	'Hanging Drop Method',
	' Others',
]
export const dropDown2 = ['48 hours', '72 hours', 'one week', 'four weeks']
export const standard_comments = {
	'Staphylococcus aureus': [
		'Erythromycin and Clindamycin NOT routinely reported on this organisms isolated from the urinary tract.',
		'Penicillin-susceptible staphylococci are also susceptible to other β-lactam agents with established clinical efficacy for staphylococcal infections. .',
		'Penicillin-resistant staphylococci are resistant to penicillinase-labile Penicillins lke Ampicillin & Amoxycillin.',
		'Penicillin Resistant Staphylococccus and MSSA, respond to Penicillinase stable Penicillins like Cloxacillin, dicloxacillin and Nafcillin .',
		'Cefoxitin or Oxacillin Resistant staphylococcus aureus is MRSA will be considered Resistant to all generations of Cepahlosporins, except Ceftaroline , Carbapenems and B -lactam combination drugs like Amoxycillin – Clavulanate, Ampicillin – Sulbactam and Piperacillin -Tazobactam.',
		'Vancomycin Susceptible S aureus become Intermediate during prolonged therapy.',
		'Vancomycin MIC ≥8ug/ml  for S aureus and MIC ≥ 32ug/ml for other Staphylococcal species should send to the reference laboratory.',
		'Gentamycin susceptible Staphylococci is used only in combination with other active agents that test susceptible.',
		'Sulfisoxazole can be used to represent any of the currently available sulfonamide preparations.',
		'Organisms susceptible to Tetracycline are also considered susceptible to Doxycycline and Minocycline but if Resistant to Tetracycline may be sensitive to Doxycycline, Minocycline, or both.',
		'Staphylococcus species may develop resistance during therapy with Quinolones. Initially susceptible may become resistant within a few days of therapy. Testing of repeat isolates are warranted..',
		'Rifampin should not be used alone for antimicrobial therapy.',
		'S.aureus susceptible to Linezolid by MIC are also considered susceptible to Tedizolid However some organism resistant to Linezolid may be susceptible to Tedizolid.',
		'Streptogramins : Quinipristin-Dalfopristin : To be reported only on MSSA.',
		'Daptomycin: Not routinely reported on organisms isolated from Lower Respiratory tract .',
		'Chloramphenicol: Nor routinely reported on organisms isolated from Urinary tract.',
		'others',
	],
	'Enterococcus species': [
		'For Enterococcus spp, Aminoglycosides, (Except High level AG testing), Cephalosporins, Clindamycin and Cotrimoxazole may appear active in vitro, but they are not effective clinically and should not be reported as susceptible..',
		'Synergy between Ampicillin, Penicillin, Vancomycin and Aminoglycosides can be predicted for Enterococci by using high level Gentamycin and Streptomycin.',
		'“Intermediate” (I) with inverted v (^) indicates agents that have the potential to concentrate in the urine.',
		'Ampicillin Sensitivity predict the susceptibility to Amoxycillin – clavulanate, Ampicillin – sulbactam, Piperacillin – Tazobactam among non – beta lactamase producing Enterococci. .',
		'Ampicillin susceptibility used to predict Imipenem susceptibility, provided the species is E.faecalis.',
		'Enterococcus susceptible to Penicillin are predictably susceptible to Ampicillin, Amoxycillin, Ampicillin – sulbactam, Amoxycillin – Clavulanate and Piperacillin – tazobactam for non – Beta lactamase species. .',
		'Susceptible to Ampicillin cannot predict susceptible to Penicillin, So Penicillin testing is required for Penicillin susceptibility..',
		'Enterococcus positive for Beta lactamase predict the resistance to Penicillin as well as amino and ureido Penicillin..',
		'Combination therapy of Penicillin, Ampicillin and Vancomycin with Aminoglycosides is indicated for serious infections like endocarditis (testing High level aminoglycosides).',
		'Dalbavancin should be reported only on Vancomycin – Susceptible E. faecalis.',
		'Daptomycin for E faecium: not to be reported in LRI.  SDD breakpoint of Daptomycin is intended to use for serious infections with this species..',
		'Macrolides: Erythromycin; Routinely not reported on organisms isolated from the Urinary tract.',
		'Susceptible to Tetracycline also considered susceptible to Doxycycline and Minocycline but Intermediate or Resistant to Tetracycline may be susceptible to Doxycycline, Minocycline, or both..',
		'Fosfomycin (U): Report only on E faecalis .',
		'Quinupristin – dalfopristin: Report only on Vancomycin -E faecium.',
		'E faecalis susceptible to Linezolid by MIC also considered susceptible to Tedizolid. Organism Intermediate or resistant to Linezolid may be susceptible to Tedizolid.',
		'others',
	],
	'Streptococcus pneumoniae': [
		'For Pneumococci: Testing Chloramphenicol, Clindamycin, Linezolid, Tedizolid, and Tetracycline by broth microdilution MIC, trailing growth can male end – point determination difficult. Trimethoprim and sulfonamides antagonists in the medium may allow slight growth: therefore, read the end point at the concentration in which there is >80% reduction in growth compared with the control..',
		'Amoxicillin, Ampicillin, Cefepime, Ceftriaxone, Cefuroxime, Ertapenem, Imipenem and Meropenem: susceptibility is determined by MIC method..',
		'Penicillin, Cefotaxime, Ceftriaxone, or Meropenem: tested by MIC method and reported with S. pneumoniae isolated from CSF .',
		'Penicillin, Cefotaxime, Ceftriaxone and Meropenem should be tested by a reliable MIC method and reported routinely with S pneumoniae isolated from CSF.  Vancomycin using the MIC or disk diffusion method.  With isolates from other sites, the oxacillin disk test may be used if the Oxacillin zone size is ≤ 19mm, Cefotaxime, Ceftriaxone, Meropenem or Penicillin MICs should be determined..',
		'Oxacillin zone sizes ≥ 20mm are susceptible (MIC ≤ 0.06ug/ml) to Penicillin. Penicillin, Cefotaxime, Ceftriaxone or Meropenem MICs should be determined for isolates with Oxacillin zone diameter ≤ 19mm..',
		'Penicillin: for all isolates other than from CSF report interpretations for both meningitis and non -meningitis.',
		'Oral Penicillin: Reported for isolates other than CSF (only MIC ).',
		'Cefepime: CSF isolates: FDA not approved and report only for non – meningitis isolates (only MIC  ≤ 0.5).',
		'Ceftriaxone: Only for meningitis in CSF isolate. Use cefotaxime or Ceftriaxone in meningitis requires therapy with maximum dose (only MIC).',
		'Cefotaxime/ Ceftriaxone: can be reported for Non – meningitis isolates (only MIC ≤ 1 ug/ml ).',
		'Cefuroxime (oral): only for non – meningitis (only MIC ≤ 1 ug/ml) .',
		'Erythromycin susceptibility predict susceptibility to Azithromycin, Clarithromycin and dithromycin. But Resistant to Erythromycin cannot predict. Routinely not reported on UTI.',
		'Organism Sensitivity to Levofloxacin is predicted for Gemifloxacin and Moxifloxacin, but resistant cannot be predicted.',
		'D -zone to be noted for S pneumoniae.',
		'others',
	],
	'B – Hemolytic Streptococcus': [
		'For Beta hemolytic Streptococcus, testing Chloramphenicol, Clindamycin, Erythromycin, Linezolid, Tedizolid and Tetracycline by broth dilution MIC, Trailing growth can make end – point determination is difficult. In such cases, read the MIC at the lowest concentration where the trailing begins. Tiny buttons of growth should be ignored..',
		'BH group includes large – colony forming pyogenic strains of Streptococci with gropu A, C or G and B. .',
		'Small colony – forming Beta hemolytic strains with Group A, C,F or G are considered part of the viridans group and break points of the viridans group should be used..',
		'Penicillin and Ampicillin are drugs of choice for treatment of β – hemolytic Streptococcal infections. Susceptibility testing of Penicillins and other β – lactams dose not need to be performed routinely because non – susceptibility is extremely rare for β – hemolytic Streptococci (Penicillin MICs > 0.12and Ampicillin > 0.25 ug/ml) and have not been reported for S.pyogenes. If testing β – hemolytic Streptococci is non – susceptible should be re-identified, re-tested and if confirmed should be sent to referral laboratory..',
		'For groups A,B,C and G β – hemolytic Streptococci, Penicillin is tested as a surrogate for Ampicillin, Amoxicillin, Amoxicillin – Clavulanate, Ampicillin – Sulbactam, Cefazolin, Cefepime, Ceftaroline, Cephradine, Cephalothin, Cefotaxime, Ceftriaxone, Ceftizoxime, Imipenem, ertapenem and Meropenem..',
		'For group  ‘A’ β – hemolytic Streptococci,  Penicillin is also a surrogate for Cefaclor, Cefdinir, Cefprozil, Ceftibuten, Cefuroxime and Cefpodoxime.',
		'Lipoglycopeptides: Dalbavancin: Report only on S.pyogenes, S agalactiae and S dysgalactiae.',
		'Lipopeptides: Daptomycin: Not reported on organisms isolated from the Lower respiratory tract.',
		'Susceptibility and resistance to Azithromycin, Clarithromycin and Dirithromycin can be predicted by testing Erythromycin and macrolides not routinely reported on organisms isolated from the Urinary tract..',
		'Erythromycin: Recommendations for intrapartum prophylaxis for GBS are Penicillin or Ampicillin. .',
		'For Penicillin allergic women at low risk for anaphylaxis, cefazolin is recommended..',
		'For high risk for anaphylaxis, Clindamycin or Vancomycin may be given.',
		'For isolates that test resistant to Erythromycin and Susceptible or Intermediate to Clindamycin, testing for CR by disk diffusion using the D -zone or by broth microdilution is required before reporting Clindamycin..',
		'Susceptible to Tetracycline also considered susceptible to Doxycycline and Minocycline but Intermediate or Resistant to Tetracycline may be susceptible to Doxycycline, Minocycline, or both..',
		' Streptogramins: Quinupristin – dalfopristin: Report only on S.pyogenes.',
		'For S. pyogenes & S agalactiae, susceptible to Linezolid by MIC also considered susceptible to Tedizolid. Organism Intermediate or resistant to Linezolid may be susceptible to Tedizolid.',
		'others',
	],
	'ENTEROBACTERALES.': [
		'AMPICILLIN (10 µg)	Result can be used to predict for Amoxicillin, Oral therapy for Uncomplicated UTIs –E.coli & P.mirabilis.',
		'CEFAZOLIN  (30 µg)	Used for other than Uncomplicated UTIs-Ec, Kp, Pm.',
		'CEFOTAXIME (30µg) or CEFTRIAXONE(30 µg)	ESBL testing by phenotypic or genotypic methods for management or Epidemiology or infection prevention purpose(IPP). Some develop resistant during therapy with third generation cephalosporins as a result of depression of AmpC B-lactamase, ie; Initially susceptible become resistant within few days after therapy. Testing subsequent isolate is needed.',
		'AMOXICILLIN or CLAVUNATE(20/10µg)	Oral therapy –Uncomplicated  UTIs or systemic infections.',
		'GENTAMICIN (10µg)	Combination therapy other than UTI.',
		'CEFAZOLIN(U) (30 µg) Surrogate for Oral Ceph	use in Uncomplicated UTIs –Ec, Kp, Pm. ( oral –cefaclor, cefdinir, cefpodoxime, cefprozil, cefuroxime, cephalexin, loracerbef. If cefazolin resistant, test these drugs individually).',
		'CEFUROXIME (30µg)	ESBL testing by phenotypic or genotypic methods for management or Epidemiology or IPP.',
		'CEFEPIME (30µg)	Susceptible / Susceptible dose dependent (SDD) result suppressed and reported  as resistant for isolates with Carbapenemase production.',
		'ERTAPENEM(10µg)	or IMIPENEM(10µg) or MEROPENEM(10µg)	Intermediate  or Reistant-check for carbapenemase production.',
		'TOBRAMYCIN (10µg) or AMIKACIN (30µg)	Combination therapy other than UTI.',
		'CEFOXITIN(30µg)	ESBL testing by phenotypic or genotypic methods for management or Epidemiology or IPP.',
		'TETRACYCLINE(30µg)	Susceptible  to TET are S to Doxy& Mino, I or R to TET may be S to Doxy & Mino.',
		'CEFTAZIDIME(30µg)	ESBL testing by phenotypic or genotypic methods for management or Epidemiology or IPP.',
		'others',
	],
	'SALMONELLA AND SHIGELLA': [
		'AMPICILLIN (10 µg)	Result can be used to predict for Amoxicillin (Shigella - poor efficacy for Amoxycillin), Oral therapy for Salmonella & Shigella.',
		'CIPROFLOXACIN (5µg) For Salmonella spp	Not susceptible- clinical failure or delayed response.',
		'LEVOFLOXACIN(5µg) For Salmonella spp	MIC only.',
		'AZITHROMYCIN (15 µg) S.Typhi only .',
		'AZITHROMYCIN (15 µg) Shigella spp only, If DDT-hazy & difficult to measure, MIC is recommended.',
		'ERTAPENEM(10µg)	I or R-check for carbapenemase production.',
		'IMIPENEM(10µg)	I or R-check for carbapenemase production.',
		'MEROPENEM(10µg)	I or R-check for carbapenemase production.',
		'TETRACYCLINE(30µg)	Susceptible to TET are S to Doxy& Mino, I or R to TET may be S to Doxy & Mino.',
		'CHLORAMPHENICOL (30 µg)	Only for extra-intestinal Salmonellosis (not UTI).',
		'others',
	],
	'PSEUDOMONAS AERUGINOSA': [
		'May develop resistance during therapy with all antimicrobial agents. Isolates initially susceptible may become resistant within a few days after therapy. Testing of repeat isolates may be warranted .',
		'TOBRAMYCIN	Does not predict susceptibility to GentamicinCombination therapy indicated other thsn UTI- P.aeruginosa.',
		'others',
	],
	others: ['others'],
}
export const specimen_nature_drop = [
	'Urine',
	'Sputum',
	'Blood',
	'Pus Aspirate',
	'Body fluids(CSF,Pleural,Ascitic)',
	'Swab',
	'Tissue Bits',
	'Curettage',
]
